### ISSUE TITLE
How to use the BSMAP methyratio file instead the bismark input file?

### ISSUE THREAD

**Issue by wangzer** [nrzabet/DMRcaller#1]
My input file is producted by BSMAP , and how can I do covert to DMRCaller input file.

**Comment by nrzabet** [comment]
Hi wangzer, 

You could write a custom script to generate this file. DMRcaller uses as input a tab delimited text file with the following columns: 
- chromosome, 
- position, 
- strand, 
- number of reads from methylated DNA, 
- number of reads from unmethylated DNA, 
- Cytosine context (CG, CHG or CHH) 
- trinucleotide context (were, instead of H, the exact nucleotide is included). 

The trinucleotide context is not used in the analysis so you can put whatever you want on that column.

**Comment by wangzer** [comment]
thanks a lot, I will try it.
![image](https://user-images.githubusercontent.com/20257218/48698102-3447d980-ec21-11e8-868c-6cc6526d24d2.png)

Another question, how do I set the range of the axis when I use the function of  plotMethylationProfileFromData()?

**Comment by nrzabet** [comment]
Sorry for the delay in the reply. You can generate the vectors with computeMethylationProfile. You will have then the individual values and you can customise the plots accordingly. 

Radu
