### ISSUE TITLE
Error during wrapup: no method or default for coercing “try-error” to “GRanges”

### ISSUE THREAD

**Issue by fixemers** [nrzabet/DMRcaller#17]
Hi, 

when I decrease the binsize from 100 to 50 or below I get the following error when running DMRcaller:

DMRcaller::computeDMRsReplicates(
    methylationData = Combined_GRanges_chr,
    condition = condition,
    context = "CG",
    method = method,
    binSize = binSize,
    test = test,
    pseudocountM = pseudocountM,
    pseudocountN = pseudocountN,
    pValueThreshold = pValueThreshold,
    minCytosinesCount = minCytosinesCount,
    minProportionDifference = minProportionDifference,
    minGap = minGap,
    minSize = minSize,
    minReadsPerCytosine = minReadsPerCytosine,
    cores = cores
  )
Parameters checking ...
Extract methylation in the corresponding context 
Compute the DMRs using  10 cores
Error during wrapup: no method or default for coercing “try-error” to “GRanges”
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

**Comment by nrzabet** [comment]
thanks for raising this issue @fixemers. This is caused by having bins without any CpG. So the smaller the bin size, the more likely it is that you will have many bins without a single CpG. This is why we recommended at least 100bp for Arabidopsis. You can use the noise filter method, which also puts weight on the distance from the CpG.

**Comment by nrzabet** [comment]
see comment above
